development:
  adapter: mysql2
  encoding: utf8mb4
  database: demo_development
  host: localhost
  username: root
  password: '123456'

test:
  adapter: mysql2
  encoding: utf8mb4
  database: demo_test
  host: localhost
  username: root
  password: '123456'

production:
  adapter: mysql2
  encoding: utf8mb4
  database: demo_production
  host: localhost
  username: root
  password: '123456'
